wandb_version: 1

epochs:
  desc: null
  value: 5
classes:
  desc: null
  value: 10
kernels:
  desc: null
  value:
  - 16
  - 32
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.005
dataset:
  desc: null
  value: MNIST
architecture:
  desc: null
  value: CNN
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706281963.562204
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      6: 4.37.0
      8:
      - 1
      - 5
      13: linux-x86_64
